server:
  port: 5005

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
    #---  zj url  ---#
      url: jdbc:mysql://localhost:3306/qy?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: zju.edu.qyTest.pojo
